[project]
name = "londonaicentre-genollama-assets" 
description = "GenoLlama assets"
authors = [
    { name = "Dr. Joe Zhang", email = "jzhang@nhs.net" },
    { name = "Sophie Ratkai", email = "s.ratkai@nhs.net" },
    { name = "Martin Chapman", email = "contact@martinchapman.co.uk" },
]
version = "1.0.0"
requires-python = ">=3.12"
license = "CC-BY-NC-ND-4.0"
dependencies = [
    "litellm>=1.80.9",
    "londonaicentre-schemallama-types",
    "pydantic>=2.12.4",
]
[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"
[tool.uv.sources]
londonaicentre-schemallama-types = { path = "../../lib/types", editable = true }
[tool.setuptools.package-data]
genollama_assets = [
    "examples/*",
    "profiles/*",
    "prompts/*",
    "structure/*",
    "*.yml",
    "py.typed"
]
[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=9.0.2",
    "ruff>=0.14.6",
]
