name: Bug
description: Raise a bug report
type: Bug
projects: ["londonaicentre/15"]
body:
  - type: input
    id: short-description
    attributes:
      label: Description
  - type: checkboxes
    id: project-admin
    attributes:
      label: Assign the relevant Milestone to this bug report
      options:
        - label: I confirm I have created/selected a Milestone corresponding to an AIC user story for this bug report
          required: true