name: Task
description: Raise a non-code task
type: Task
projects: ["londonaicentre/15"]
body:
  - type: input
    id: short-description
    attributes:
      label: Description
  - type: checkboxes
    id: project-admin
    attributes:
      label: Assign the relevant Milestone to this task
      options:
        - label: I confirm I have created/selected a Milestone corresponding to an AIC user story for this task
          required: true
