[project]
name = "londonaicentre-oncollama" 
description = "OncoLlama"
authors = [
    { name = "Dr. Joe Zhang", email = "jzhang@nhs.net" },
]
version = "1.0.0"
requires-python = ">=3.12"
license = "CC-BY-NC-ND-4.0"
dependencies = [
    "londonaicentre-oncollama-assets",
    "londonaicentre-schemallama-docsynth"
]
[project.scripts]
"docsynth" = "oncollama.docsynth:main"
"bootstrap" = "oncollama.bootstrap:main"
"datagen" = "oncollama.datagen:main"
[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"
[tool.uv.sources]
londonaicentre-oncollama-assets = { path = "../../assets/oncollama", editable = true }
londonaicentre-schemallama-docsynth = { path = "../../lib/docsynth", editable = true }
londonaicentre-schemallama-datagen = { path = "../../lib/datagen", editable = true }
[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "ruff>=0.14.6",
]
