[project]
name = "londonaicentre-genollama" 
description = "GenoLlama"
authors = [
    { name = "Dr. Joe Zhang", email = "jzhang@nhs.net" },
    { name = "Sophie Ratkai", email = "s.ratkai@nhs.net" },
    { name = "Martin Chapman", email = "contact@martinchapman.co.uk" },
]
version = "1.0.0"
requires-python = ">=3.12"
license = "CC-BY-NC-ND-4.0"
dependencies = [
    "python-dotenv>=1.2.1",
]
[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"
[tool.uv.sources]
londonaicentre-genollama-assets = { path = "../../assets/genollama", editable = true }
londonaicentre-schemallama-datagen = { path = "../../lib/datagen", editable = true }
[dependency-groups]
dev = [
    "londonaicentre-genollama-assets",
    "londonaicentre-schemallama-datagen",
]
