[project]
name = "paedawen"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "londonaicentre-docsynth",
    "londonaicentre-mesa-datagen",
    "londonaicentre-paedacuteschema>=1.2.0",
    "mesa-runtime",
]

[tool.uv.sources]
londonaicentre-docsynth = { git = "ssh://git@github.com/londonaicentre/MESA-Docsynth", branch = "spike/mesa-build-refactor" }
londonaicentre-mesa-datagen = { path = "../../lib/datagen", editable = true }
mesa-runtime = { git = "https://github.com/londonaicentre/mesa-runtime.git", subdirectory = "lib" }
