name: entityschema test

on:
  pull_request:
    branches:
      - main
    paths:
      - schemas/entityschema/**

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      working-directory: schemas/entityschema
