name: genollama assets test

on:
  pull_request:
    branches:
      - main
    paths:
      - assets/genollama/**

jobs:
  test:
    runs-on: codebuild-londonaicentre-org-runner-${{ github.run_id }}-${{ github.run_attempt }}
    defaults:
      run:
        working-directory: assets/genollama
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v4
      - run: uv sync
      - run: uv run ruff check src/ tests/
      - run: uv run mypy src/ tests/
      - run: uv run pytest tests
