name: build and publish llamaserve

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build-and-publish:
    if: startsWith(github.event.release.tag_name, 'llamaserve')
    runs-on: codebuild-londonaicentre-org-runner-${{ github.run_id }}-${{ github.run_attempt }}
    environment: ${{ github.event_name == 'release' && 'pypi' || 'testpypi' }}
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: lib/infer/local/llamaserve
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --only-dev
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ github.event_name == 'release' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
