name: llamaserve test

on:
  pull_request:
    branches:
      - main
    paths:
      - lib/infer/local/llamaserve/**

jobs:
  test:
    runs-on: codebuild-londonaicentre-org-runner-${{ github.run_id }}-${{ github.run_attempt }}
    defaults:
      run:
        working-directory: lib/infer/local/llamaserve
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: |
          uv sync --only-dev
          source .venv/bin/activate
      - run: flake8 src/ tests/
      - run: mypy src/ tests/
      - run: pytest tests