name: oncoschema test

on:
  pull_request:
    branches:
      - main
    paths:
      - schemas/oncoschema/**

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      working-directory: schemas/oncoschema
