name: build and publish opnoteschema

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "schemas/opnoteschema/**"

jobs:
  build-and-publish:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: ./.github/workflows/build-and-publish.yml
    with:
      working-directory: schemas/opnoteschema
      package: opnoteschema
