name: build and publish types

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "lib/types/**"

jobs:
  build-and-publish:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: ./.github/workflows/build-and-publish.yml
    with:
      working-directory: lib/types
      package: types
